# Ref: https://github.com/gitpod-io/gitpod/issues/6283#issuecomment-1001043454
tasks:
  - init: ./configure && timeout 50m make -j16 || true

# Ref: https://www.gitpod.io/docs/prebuilds#github-specific-configuration
github:
  prebuilds:
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
