comment:
  # Only show diff and files changed:
  layout: "diff, files"
  # Don't post if no changes in coverage:
  require_changes: true

codecov:
  notify:
    # Wait for all coverage builds:
    after_n_builds: 2
