name: node ASAN

on: [push, pull_request]

jobs:
  ubuntu-build:
      runs-on: ubuntu-latest
      container: gengjiawen/node-build:2020-02-14
      steps:
        - uses: actions/checkout@v2
        - name: Build
          # TODO(mmarchini): With V8 8.1, GitHub Actions doesn't have enough
          # memory to build with debug and ASAN. Allow this build to fail until
          # we figure out a workaround, or until we update to 8.2 (where build
          # is passing).
          continue-on-error: true
          run: |
              npx envinfo
              ./configure --debug --enable-asan --ninja && ninja -C out/Debug
        - name: Test
          env:
            ASAN_OPTIONS: halt_on_error=0
          continue-on-error: true
          run: |
            python3 tools/test.py -J --mode=debug
