name: node ASAN

on: [push, pull_request]

jobs:
  ubuntu-build:
      runs-on: ubuntu-latest
      container: gengjiawen/node-build:2020-02-14
      steps:
        - uses: actions/checkout@v2
        - name: Build
          run: |
              npx envinfo
              ./configure --debug --enable-asan --ninja && ninja -C out/Debug
        - name: Test
          env:
            ASAN_OPTIONS: halt_on_error=0
          continue-on-error: true
          run: |
            python3 tools/test.py -J --mode=debug
