name: Auto Start CI

on:
  schedule:
    # Runs every five minutes (fastest the scheduler can run). Five minutes is
    # optimistic, it can take longer to run.
    # To understand why `schedule` is used instead of other events, refer to
    # ./doc/guides/commit-queue.md
    - cron: "*/5 * * * *"

env:
  NODE_VERSION: lts/*

jobs:
  startCI:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Install dependencies
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install node-core-utils
        run: npm install -g node-core-utils

      - name: Setup node-core-utils
        run: |
          ncu-config set username ${{ secrets.JENKINS_USER }}
          ncu-config set token none
          ncu-config set jenkins_token ${{ secrets.JENKINS_TOKEN }}
          ncu-config set owner "${{ github.repository_owner }}"
          ncu-config set repo "$(echo ${{ github.repository }} | cut -d/ -f2)"

      - name: Start the CI
        run: |
          PRs=$(gh pr list --label 'request-ci' --json number --jq 'map(.number) | .[]' --limit 100)
          ./tools/actions/start-ci.sh "$PRs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
