name: "First commit message adheres to guidelines at https://goo.gl/p2fr5Q"

on: [pull_request]

env:
  NODE_VERSION: lts/*

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Validate commit message
        run: |
          echo "::add-matcher::.github/workflows/commit-lint-problem-matcher.json"
          git rev-parse HEAD^ | xargs npx -q core-validate-commit --no-validate-metadata --tap
